[package]
name = "kitty"
version = "0.1.0"
authors = ["Adrian Borup <adrian@borup.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
colored = "2.0.0"
reqwest = "0.10.8"
tokio = { version = "0.2.22", features = ["macros"] }
tempfile = "3.1.0"
zip = "0.5.8"
